include:
  - '/gitlab/ci/unit.yml'
  - '/gitlab/ci/integration.yml'
  - '/gitlab/ci/webstandard.yml'
  - '/gitlab/ci/template.yml'

stages:
  - test
  - integration
  - accessibility
  - unit
  - style
  - ci_checks

image: domjudge/gitlabci:24.04
