rm -rf	diff-contests.txt
rm -rf	diff-submissions.txt
rm -rf	event-feed?stream=0
rm -rf	portforward.ps1
rm -rf	webapp/public/style_browserhack.css
rm -rf	webapp/public/style_me.css
rm -rf	aclocal.m4
rm -rf	bin/
rm -rf	config.log
rm -rf	config.status
rm -rf	configure
rm -rf	doc/manual/build/
rm -rf	doc/manual/conf_ref.rst
rm -rf	doc/manual/html
rm -rf	doc/manual/substitutions.py
rm -rf	doc/manual/team
rm -rf	doc/manual/version.py
rm -rf	etc/apache.conf
rm -rf	etc/config.h
rm -rf	etc/config.h.in
rm -rf	etc/domjudge-fpm.conf
rm -rf	etc/domserver-static.php
rm -rf	etc/judgehost-static.php
rm -rf	etc/nginx-conf
rm -rf	etc/nginx-conf-inner
rm -rf	etc/runguard-config.h
rm -rf	etc/sudoers-domjudge
rm -rf	etc/symfony_app.secret
rm -rf	example_problems/boolfind.zip
rm -rf	example_problems/contest.yaml
rm -rf	example_problems/fltcmp.zip
rm -rf	example_problems/hello.zip
rm -rf	judge/chroot-startstop.sh
rm -rf	judge/create-cgroups.service
rm -rf	judge/create_cgroups
rm -rf	judge/domjudge-judgedaemon@.service
rm -rf	judge/evict
rm -rf	judge/judgedaemon
rm -rf	judge/runguard
rm -rf	judge/runguard.o
rm -rf	judge/runpipe
rm -rf	lib/dj_utils.py
rm -rf	lib/judge
rm -rf	lib/lib.error.o
rm -rf	lib/lib.misc.o
rm -rf	lib/vendor/
rm -rf	misc-tools/__pycache__/
rm -rf	misc-tools/configure-domjudge
rm -rf	misc-tools/dj_judgehost_cleanup
rm -rf	misc-tools/dj_make_chroot
rm -rf	misc-tools/dj_make_chroot_docker
rm -rf	misc-tools/dj_run_chroot
rm -rf	misc-tools/fix_permissions
rm -rf	misc-tools/import-contest
rm -rf	output/
rm -rf	paths.mk
rm -rf	sql/dj_setup_database
rm -rf	sql/files/config.h
rm -rf	sql/files/defaultdata/adb.zip
rm -rf	sql/files/defaultdata/awk.zip
rm -rf	sql/files/defaultdata/bash.zip
rm -rf	sql/files/defaultdata/c.zip
rm -rf	sql/files/defaultdata/compare.zip
rm -rf	sql/files/defaultdata/cpp.zip
rm -rf	sql/files/defaultdata/csharp.zip
rm -rf	sql/files/defaultdata/f95.zip
rm -rf	sql/files/defaultdata/full_debug.zip
rm -rf	sql/files/defaultdata/hs.zip
rm -rf	sql/files/defaultdata/java_javac.zip
rm -rf	sql/files/defaultdata/java_javac_detect.zip
rm -rf	sql/files/defaultdata/js.zip
rm -rf	sql/files/defaultdata/kt.zip
rm -rf	sql/files/defaultdata/lua.zip
rm -rf	sql/files/defaultdata/pas.zip
rm -rf	sql/files/defaultdata/pl.zip
rm -rf	sql/files/defaultdata/plg.zip
rm -rf	sql/files/defaultdata/py3.zip
rm -rf	sql/files/defaultdata/r.zip
rm -rf	sql/files/defaultdata/rb.zip
rm -rf	sql/files/defaultdata/rs.zip
rm -rf	sql/files/defaultdata/run.zip
rm -rf	sql/files/defaultdata/scala.zip
rm -rf	sql/files/defaultdata/sh.zip
rm -rf	sql/files/defaultdata/swift.zip
rm -rf	webapp/.phpunit.result.cache
rm -rf	webapp/config/autoload.php
rm -rf	webapp/config/static.yaml
rm -rf	webapp/public/bundles/
rm -rf	webapp/var/cache/dev/
rm -rf	webapp/var/cache/test/
rm -rf	webapp/var/log/dev.log
rm -rf	webapp/var/log/event-feed-importer.log
rm -rf	webapp/var/log/test.log
