name: Check creation of chroot
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'

jobs:
  debian-family:
    strategy:
      matrix:
        ARCH:
          - arm64
          - armhf
          - i386
        version: [jammy, focal, rolling]
        os: [ubuntu]
        releaseBranch:
          - ${{ contains(github.ref, 'main') }}
        exclude:
          - releaseBranch: false
        include:
          - DEFAULT: ""
          - ARCH: amd64
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    steps:
      - name: Install git so we get the .github directory
        run: apt-get update; apt-get install -y git
      - uses: actions/checkout@v4
      - name: Setup image and run bats tests
        run: .github/jobs/chroot-checks/setup_configure_image.sh "chroot" "judgehost"
