name: Unit tests
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [mariadb, mysql]
    services:
      sqlserver:
        image: ${{ matrix.db }}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: domjudge
          MYSQL_PASSWORD: domjudge
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Install DOMjudge
        run: .github/jobs/baseinstall.sh admin

