name: Webstandard (WCAG, W3C)
on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+'

jobs:
  standards:
    runs-on: ubuntu-latest
    container:
      image: domjudge/gitlabci:24.04
    strategy:
      matrix:
        role: [team, balloon, jury]
        db: [bare-install, install]
        releaseBranch:
          - ${{ contains(github.ref, 'main') }}
        exclude:
          - releaseBranch: false
        include:
          - role: public
            db: install
          - role: public
            db: bare-install
          - role: admin
            db: install
          - role: admin
            db: bare-install
    steps:
      - uses: actions/checkout@v4
      - name: Install DOMjudge
        run: .github/jobs/baseinstall.sh ${{ matrix.role }}
      - name: Run webstandard tests (W3C, WCAG)
        run: .github/jobs/webstandard.sh
      - name: Upload all logs/artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.version }}-logs
          path: |
            /tmp/artifacts
            /var/log/nginx
            /opt/domjudge/domserver/webapp/var/log/*.log
